# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "def9a09dfbc4a80f447c70613ba22f96"
name = "wishlist"
handle = "wishlist-390"
application_url = "https://mod-respective-connections-outsourcing.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-4eb13a2e.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders, write_orders"

[auth]
redirect_urls = [
  "https://mod-respective-connections-outsourcing.trycloudflare.com/auth/callback",
  "https://mod-respective-connections-outsourcing.trycloudflare.com/auth/shopify/callback",
  "https://mod-respective-connections-outsourcing.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false

