# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5344a8023315a3345ed63613b4868c44"
name = "wishlist-inspire"
handle = "wishlist-inspire-156"
application_url = "https://wordpress-secrets-station-vegetarian.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-4eb13a2e.myshopify.com"

[auth]
redirect_urls = [
  "https://wordpress-secrets-station-vegetarian.trycloudflare.com/auth/callback",
  "https://wordpress-secrets-station-vegetarian.trycloudflare.com/auth/shopify/callback",
  "https://wordpress-secrets-station-vegetarian.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
